// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PplHZm9zJwCOse0N1SnYKK9mBFhga0Y',
    appId: '1:853597593530:web:8739d8b730fc6181f98783',
    messagingSenderId: '853597593530',
    projectId: 'task1-efcea',
    authDomain: 'task1-efcea.firebaseapp.com',
    storageBucket: 'task1-efcea.firebasestorage.app',
    measurementId: 'G-D7M36X7WWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kaeR7ETS5GXOXgC4ayd3_eag40hlgRw',
    appId: '1:853597593530:android:3e6b14040b810a59f98783',
    messagingSenderId: '853597593530',
    projectId: 'task1-efcea',
    storageBucket: 'task1-efcea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0GcrHgCL8tGkfpwdQreWTkStGLEymgHw',
    appId: '1:853597593530:ios:2c310c4f2f696741f98783',
    messagingSenderId: '853597593530',
    projectId: 'task1-efcea',
    storageBucket: 'task1-efcea.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0GcrHgCL8tGkfpwdQreWTkStGLEymgHw',
    appId: '1:853597593530:ios:2c310c4f2f696741f98783',
    messagingSenderId: '853597593530',
    projectId: 'task1-efcea',
    storageBucket: 'task1-efcea.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2PplHZm9zJwCOse0N1SnYKK9mBFhga0Y',
    appId: '1:853597593530:web:8a077cb51d9490f1f98783',
    messagingSenderId: '853597593530',
    projectId: 'task1-efcea',
    authDomain: 'task1-efcea.firebaseapp.com',
    storageBucket: 'task1-efcea.firebasestorage.app',
    measurementId: 'G-GEWLZGE1Z9',
  );

}